
export const dataTable = [
    { no: "01", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "02", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "03", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "04", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "05", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "06", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "07", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "08", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "09", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "10", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "11", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "12", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "13", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "14", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "15", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
    { no: "16", business_name: 'Mission Pet Hospital', service_name: 'Checkup', subService_name: 'General checkups Annual Wellness Exam Hospitalization', business_email: "Edwin.McClure@hotmail.com", phone_no: "359.883.2932", address: '720 Valencia St, San Francisco CA 95110, United States', licenses: 'View', action: '' },
]
